# 01 지능형 로봇을 위한 시각지능_v4.pdf

## 8p~

In [20]:
# 흑백greyscale
import numpy as np
from PIL import Image

image = np.array(
[[255, 255, 255],
 [255, 0, 0],
 [255, 255,  0]]
)

print(image.shape)
print(image[1][2])

img = Image.fromarray(image)
img.show()

(3, 3)
0


In [30]:
# 컬러color
image = np.array(
[[[255, 255, 255],[0, 0, 0],[128, 128, 128]],
 [[255, 0, 0],[0, 255, 0],[0, 0, 255]],
 [[255, 255,  0],[255, 0, 255],[0, 255, 255]]]
)

print(image.shape)
print(image[1][2][2])

img = Image.fromarray(image.astype(np.uint8))
img.show()

(3, 3, 3)
255


In [47]:
# 상하 뒤집기
color_image = np.array(
[ [[255, 255, 255],[0, 0, 0],[128, 128, 128]],
  [[255, 0, 0],[0, 255, 0],[0, 0, 255]],
  [[255, 255,  0],[255, 0, 255],[0, 255, 255]] ]
)

reversed_image = np.array(image[0])

# print(color_image.shape)
# print(color_image[1][2][2])


# clrimg = Image.fromarray(color_image.astype(np.uint8))
# clrimg.show()
# r_image = Image.fromarray(reversed_image.astype(np.uint8))
# r_image.show()

array([[255, 255, 255],
       [  0,   0,   0],
       [128, 128, 128]])

In [48]:
image[0]

array([[255, 255, 255],
       [  0,   0,   0],
       [128, 128, 128]])

In [55]:
newimage = image[2]
newimage = np.vstack([newimage, image[1], image[0]])
reversed_image = np.array(newimage)
print(reversed_image)

#shape을 써서...?

[[255 255   0]
 [255   0 255]
 [  0 255 255]
 [255   0   0]
 [  0 255   0]
 [  0   0 255]
 [255 255 255]
 [  0   0   0]
 [128 128 128]]


# 9p. Affine Transform

In [56]:
import numpy as np
import cv2 #openCV 라이브러리

In [ ]:
img = cv2.imread('checkerboard_pattern.png')
# 이미지가 컬러로 되어있을 수도 있으므로 BGR로 변경
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

#점point 추가
pts1 = np.float32([[100, 100], [180, 100], [200,200]])
pts2 = np.float32([[100, 100], [190, 120], [220,220]])

M = cv2.getAffineTransform(pts1, pts2)
dst = cv2.warpAffine(img, M, img.shape[:2])

cv2.circle(img, pts1[0].astype(np.uint8), 2, (255,0,0), 2)
cv2.circle(img, pts1[1].astype(np.uint8), 2, (0,255,0), 2)
cv2.circle(img, pts1[2].astype(np.uint8), 2, (0,0,255), 2)

cv2.circle(dst, pts2[0].astype(np.uint8), 2, (255,0,0), 2)
cv2.circle(dst, pts2[1].astype(np.uint8), 2, (0,255,0), 2)
cv2.circle(dst, pts2[2].astype(np.uint8), 2, (0,0,255), 2)

cv2.imshow('Original', img)
cv2.imshow('Affine', dst)

cv2.waitKey(0)
cv2.destroyAllWindows